# Roxygen2 documentation for built-in package datasets.
#
# The datasets are generated by data-raw/prepare_datasets.R and stored as
# compressed .rda files in data/.

# ── milt_air ─────────────────────────────────────────────────────────────────

#' AirPassengers as a milt-ready tibble
#'
#' Monthly totals of international airline passengers (thousands), January 1949
#' to December 1960.  This is the classic Box & Jenkins dataset repackaged as a
#' plain tibble so it can be passed directly to [milt_series()].
#'
#' @format A [tibble::tibble()] with 144 rows and 2 columns:
#' \describe{
#'   \item{date}{`Date`. First day of each month.}
#'   \item{value}{`numeric`. Total passengers (thousands).}
#' }
#'
#' @source Base R dataset \code{\link[datasets]{AirPassengers}}.
#'   Box, G. E. P., Jenkins, G. M., and Reinsel, G. C. (1976)
#'   *Time Series Analysis, Forecasting and Control*, 3rd ed.
#'   Holden-Day. Series G.
#'
#' @seealso [milt_series()], [milt_retail], [milt_energy]
#' @family datasets
#' @examples
#' \donttest{
#' data(milt_air)
#' s <- milt_series(milt_air, time_col = "date", value_cols = "value",
#'                  frequency = "monthly")
#' s
#' }
"milt_air"


# ── milt_retail ───────────────────────────────────────────────────────────────

#' Synthetic multi-series monthly retail sales
#'
#' Monthly sales figures (synthetic) for five product categories from January
#' 2010 to December 2022 (156 months each).  Each series exhibits a linear
#' trend, monthly seasonality, and Gaussian noise, making this dataset suitable
#' for multi-series forecasting demonstrations.
#'
#' @format A [tibble::tibble()] with 780 rows (5 categories \eqn{\times} 156
#'   months) and 3 columns:
#' \describe{
#'   \item{date}{`Date`. First day of each month.}
#'   \item{category}{`character`. One of `"Electronics"`, `"Clothing"`,
#'     `"Food"`, `"Furniture"`, `"Toys"`.}
#'   \item{sales}{`numeric`. Monthly sales in arbitrary units (non-negative).}
#' }
#'
#' @source Synthetically generated by `data-raw/prepare_datasets.R`.
#'
#' @seealso [milt_series()], [milt_air], [milt_energy]
#' @family datasets
#' @examples
#' \donttest{
#' data(milt_retail)
#' elec <- milt_retail[milt_retail$category == "Electronics", ]
#' s <- milt_series(elec, time_col = "date", value_cols = "sales",
#'                  frequency = "monthly")
#' s
#' }
"milt_retail"


# ── milt_energy ───────────────────────────────────────────────────────────────

#' Synthetic hourly energy consumption with covariates
#'
#' Hourly electricity consumption (MWh) for a single site over 60 consecutive
#' days (1 440 observations), together with temperature and a weekend indicator.
#' Designed for covariate-aware forecasting examples.
#'
#' @format A [tibble::tibble()] with 1 440 rows and 4 columns:
#' \describe{
#'   \item{datetime}{`POSIXct` (UTC). Timestamp at the start of each hour.}
#'   \item{consumption}{`numeric`. Energy consumed during the hour (MWh,
#'     non-negative).}
#'   \item{temperature}{`numeric`. Ambient temperature in degrees Celsius.}
#'   \item{is_weekend}{`integer`. `1` on Saturday or Sunday, `0` otherwise.}
#' }
#'
#' @source Synthetically generated by `data-raw/prepare_datasets.R`.
#'
#' @seealso [milt_series()], [milt_air], [milt_retail], [milt_add_covariates()]
#' @family datasets
#' @examples
#' \donttest{
#' data(milt_energy)
#' s <- milt_series(milt_energy,
#'                  time_col   = "datetime",
#'                  value_cols = "consumption",
#'                  frequency  = "hourly")
#' s
#' }
"milt_energy"
